FROM python:3.11-slim

WORKDIR /app

# Instalar curl para health check
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY servico-b/requirements.txt .

RUN pip install -r requirements.txt

COPY servico-b/app.py .

EXPOSE 5002

CMD ["python", "app.py"]